/*
  Translation dictionary for multi‑language support. Keys are phrases
  used throughout the website and values contain translations for
  supported languages. Additional languages can be added by
  extending the object with new locale codes. The application
  selects the appropriate translation based on the user’s choice.
*/

const translations = {
  en: {
    hero_title: 'Find the perfect stay for your trip',
    hero_subtitle: 'Book hotels, villas and more across Asia',
    search_destination: 'Destination',
    search_checkin: 'Check‑in',
    search_checkout: 'Check‑out',
    search_guests: 'Guests',
    search_button: 'Search',
    popular_destinations: 'Popular Destinations',
    featured_deals: 'Featured Deals',
    filters: 'Filters',
    sort_by: 'Sort by',
    price_low_high: 'Price: Low to High',
    price_high_low: 'Price: High to Low',
    rating_high_low: 'Rating: High to Low',
    popularity: 'Popularity',
    hotel_details: 'Hotel Details',
    amenities: 'Amenities',
    room_types: 'Room Types',
    reviews: 'Reviews',
    book_now: 'Book Now',
    booking: 'Booking',
    guest_details: 'Guest Details',
    confirm_booking: 'Confirm Booking',
    login: 'Login',
    register: 'Register',
    username: 'Username',
    password: 'Password',
    full_name: 'Full Name',
    email: 'Email',
    dashboard: 'Dashboard',
    admin_panel: 'Admin Panel',
    manage_hotels: 'Manage Hotels',
    manage_bookings: 'Manage Bookings',
    manage_users: 'Manage Users',
    add_hotel: 'Add Hotel',
    edit_hotel: 'Edit Hotel',
    delete: 'Delete',
    update: 'Update',
    save: 'Save',
    cancel: 'Cancel',
    languages: 'Languages',
    log_out: 'Log Out',
    booking_history: 'Booking History',
    saved_hotels: 'Saved Hotels',
    no_bookings: 'You have no bookings yet.',
    remove: 'Remove',

    // Additional keys for extended features
    location_map: 'Location',
    add_review: 'Add Review',
    rating_label: 'Rating',
    comment_label: 'Comment',
    submit_review: 'Submit',
    review_thanks: 'Thank you for your review!',
    facilities: 'Facilities',
    phone: 'Phone',
    booking_summary: 'Booking Summary',
    total: 'Total',
    confirm_payment: 'Confirm Payment',
    pay_now: 'Pay Now',
    card_number: 'Card Number',
    expiry: 'Expiry Date',
    cvv: 'CVV',
  },
  id: {
    hero_title: 'Temukan tempat menginap terbaik untuk perjalanan Anda',
    hero_subtitle: 'Pesan hotel, villa, dan lainnya di seluruh Asia',
    search_destination: 'Destinasi',
    search_checkin: 'Masuk',
    search_checkout: 'Keluar',
    search_guests: 'Tamu',
    search_button: 'Cari',
    popular_destinations: 'Destinasi Populer',
    featured_deals: 'Penawaran Unggulan',
    filters: 'Filter',
    sort_by: 'Urutkan berdasarkan',
    price_low_high: 'Harga: Rendah ke Tinggi',
    price_high_low: 'Harga: Tinggi ke Rendah',
    rating_high_low: 'Rating: Tinggi ke Rendah',
    popularity: 'Popularitas',
    hotel_details: 'Detail Hotel',
    amenities: 'Fasilitas',
    room_types: 'Tipe Kamar',
    reviews: 'Ulasan',
    book_now: 'Pesan Sekarang',
    booking: 'Pemesanan',
    guest_details: 'Detail Tamu',
    confirm_booking: 'Konfirmasi Pemesanan',
    login: 'Masuk',
    register: 'Daftar',
    username: 'Nama Pengguna',
    password: 'Kata Sandi',
    full_name: 'Nama Lengkap',
    email: 'Email',
    dashboard: 'Dasbor',
    admin_panel: 'Panel Admin',
    manage_hotels: 'Kelola Hotel',
    manage_bookings: 'Kelola Pemesanan',
    manage_users: 'Kelola Pengguna',
    add_hotel: 'Tambah Hotel',
    edit_hotel: 'Edit Hotel',
    delete: 'Hapus',
    update: 'Perbarui',
    save: 'Simpan',
    cancel: 'Batal',
    languages: 'Bahasa',
    log_out: 'Keluar',
    booking_history: 'Riwayat Pemesanan',
    saved_hotels: 'Hotel Favorit',
    no_bookings: 'Anda belum memiliki pemesanan.',
    remove: 'Hapus',

    // Additional keys for extended features
    location_map: 'Lokasi',
    add_review: 'Tambah Ulasan',
    rating_label: 'Peringkat',
    comment_label: 'Komentar',
    submit_review: 'Kirim',
    review_thanks: 'Terima kasih atas ulasan Anda!',
    facilities: 'Fasilitas',
    phone: 'Telepon',
    booking_summary: 'Ringkasan Pemesanan',
    total: 'Total',
    confirm_payment: 'Konfirmasi Pembayaran',
    pay_now: 'Bayar Sekarang',
    card_number: 'Nomor Kartu',
    expiry: 'Tanggal Kedaluwarsa',
    cvv: 'CVV',
  },
};

// Gets translation by key and current language
function t(key, lang = currentLang) {
  const dict = translations[lang] || translations.en;
  return dict[key] || key;
}

// Default language
let currentLang = 'en';